/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReportPublisherRole;

import Business.Enterprise.Enterprise;
import Business.GmailClient.GmailClient;
import Business.Organization.HealthOrganization;
import Business.Organization.Organization;
import Business.Organization.ReportingOrganization;
import Business.UserAccount.UserAccount;
import Business.Utils.MyEmailVerifier;
import Business.WorkQueue.HealthReportWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author NARESH SHAH
 */
public class HealthReportByMailJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private ReportingOrganization organization;
    private Enterprise enterprise;
    private UserAccount account;
    private WorkRequest request;
    private String HtmlMessage;
    
    /**
     * Creates new form HealthReportByMailJPanel
     */
    public HealthReportByMailJPanel(JPanel userProcessContainer,UserAccount account,ReportingOrganization organization,Enterprise enterprise,WorkRequest request,String HtmlMessge) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.HtmlMessage=HtmlMessge;
        MyEmailVerifier myEmailVerifier= new MyEmailVerifier();
        txtEmailId.setInputVerifier(myEmailVerifier);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbRequest = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSub = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMailMessage = new javax.swing.JTextArea();
        requestTestJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        cmbRequest.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " Please Select Mode:", "Email", "Courier", "Post", "Hand to Hand" }));
        cmbRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRequestActionPerformed(evt);
            }
        });

        jLabel1.setText("Address");

        jLabel2.setText("Receiver's Email Id:");

        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });

        jLabel3.setText("Subject");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jLabel6.setText("Mail Message");

        jLabel5.setText("Mode of Sending Request");

        txtMailMessage.setColumns(20);
        txtMailMessage.setRows(5);
        jScrollPane3.setViewportView(txtMailMessage);

        requestTestJButton.setText("Send to Health Organisation");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addComponent(backJButton)
                .addGap(64, 64, 64)
                .addComponent(requestTestJButton)
                .addGap(120, 120, 120))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(23, 23, 23)
                            .addComponent(cmbRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSub, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(110, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(483, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestTestJButton)
                    .addComponent(backJButton))
                .addGap(36, 36, 36))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGap(39, 39, 39)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(46, 46, 46)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSub, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addContainerGap(87, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        String message = (String)cmbRequest.getSelectedItem();
        if(message.equalsIgnoreCase("Please Select Mode:")){
            JOptionPane.showMessageDialog(null, "Please Select The Mode Of Sending");
        }
        else if(message.equalsIgnoreCase("Courier") || message.equalsIgnoreCase("Post") || message.equalsIgnoreCase("Hand to Hand"))
        {
        }
        else{ 
             if(txtEmailId.getText().isEmpty() )
            {   JOptionPane.showMessageDialog(null, "Please Provide Email Id of Sender");
                return;
            }
            if(txtMailMessage.getText().isEmpty())
            {
               JOptionPane.showMessageDialog(null, "Please Provide Mail Message For Sender");
                return; 
            }
            if(txtSub.getText().isEmpty())
            {
               JOptionPane.showMessageDialog(null, "Please Provide Subject For Sender");
                return; 
            }
            String mailFrom=new String("shikha001688235@gmail.com");

            //Sender must be a Gmail Account holder

            String mailTo=txtEmailId.getText();
            //but here you can send to any type of mail account

            String senderPassword=new String("001688235");

            String senderUserName=new String("shikha001688235@gmail.com");
            Boolean isHtml=true;
            //if mail send as html then ishmtl=true else ishtml=false

            //Mention your email subject and content

            String mailSubject=txtSub.getText();

            String mailText=txtMailMessage.getText()+"<p>&nbsp;</p>"+HtmlMessage;
            //String mailText=HtmlMessage;

            //Create a GmailClient object

            GmailClient newGmailClient=new GmailClient();

            //Setting up account details

            newGmailClient.setAccountDetails(senderUserName, senderPassword);

            //Send mail

            newGmailClient.sendGmail(mailFrom, mailTo, mailSubject, mailText,isHtml);

            //Receive mails

            //.readGmail();

        }
        HealthReportWorkRequest request = new HealthReportWorkRequest();
        request.setModeOfreceive(message);
        request.setSender(account);
        request.setStatus("Completed");
        request.setOrganizationType("Health");

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof HealthOrganization){
                org = organization;
                break;
            }
        }

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof ReportingOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null, "Details Added Successfully And Request Sent");
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        HealthAnalystReportJPanel hawjp = (HealthAnalystReportJPanel) component;
        //hawjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void cmbRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRequestActionPerformed
        // TODO add your handling code here:
         String message = (String)cmbRequest.getSelectedItem();
        if(message.equalsIgnoreCase("Please Select Mode:")){
             JOptionPane.showMessageDialog(null, "Please Select The Mode Of Sending");
             return;
        }
        else if(message.equalsIgnoreCase("Courier") || message.equalsIgnoreCase("Post") || message.equalsIgnoreCase("Hand to Hand"))
        {   txtAddress.setEnabled(true);
            txtEmailId.setEnabled(false);
            txtSub.setEnabled(false);
            txtMailMessage.setEnabled(false);
            
        }
        else{
            txtAddress.setEnabled(false);
            txtEmailId.setEnabled(true);
            txtSub.setEnabled(true);
            txtMailMessage.setEnabled(true);
            
        }
    }//GEN-LAST:event_cmbRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox cmbRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextArea txtMailMessage;
    private javax.swing.JTextField txtSub;
    // End of variables declaration//GEN-END:variables
}
